# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  meteoasv-api:
    image: jtorregrosa/meteoasv-api:0.0.1-SNAPSHOT
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: ./environments/.env
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:8080:8080"
  meteoasv-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    # volumes:
    #   - ~/volumes/meteoasv/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - discovery.type=single-node
